name: DevOpsPractical23
run-name: Build and test DevOpsPractical23
on: [push]
jobs:
  test:
    name: Swiftlint checks
    runs-on: macOS-latest
    steps:
         run: |
          ls -al
          sudo gem install cocoapods
          pod install --repo-update
          ls -al
          Pods/SwiftLint/swiftlint DevOpsPractical24
               Explore-GitHub-Actions:
          - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          - name: Check out repository code
            uses: actions/checkout@v4
          - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          - name: List files in the repository
            run: |
              ls ${{ github.workspace }}
          - run: echo "ğŸ This job's status is ${{ job.status }}."
